### ISSUE TITLE
Support for `#[should_panic]`?

### ISSUE THREAD

**Issue by mgeisler** [google/googletest-rust#328] opened 2023-11-29 22:23 UTC
Hi there! I wanted to write about GoogleTest for Comprehensive Rust, so I tried adding a failing test:

```rust
#[googletest::test]
fn two_logged_failures() {
    let value = 2;
    expect_that!(value, eq(4)); // Test now failed, but continues executing.
    expect_that!(value, eq(5)); // Second failure is also logged.
}
```

So far so good! However, now my `cargo test` fails — on purpose.

I went looking for something similar to [Testing panics](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#testing-panics), but when I add the `#[should_panic]`, I'm told that this isn't supported:

```
% cargo test
   Compiling testing v0.1.0 (/home/mgeisler/src/comprehensive-rust/src/testing)
error: functions using `#[should_panic]` must return `()`
 --> src/testing/googletest.rs:4:1
  |
4 | #[googletest::test]
  | ^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `googletest::test` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `testing` (example "googletest-example" test) due to previous error
```

It does not help to return `()` — I suppose it's because the test body returns something else due to `googletest::test`?

Is it possible for me to silence the expected error?

**Comment by hovinen** [comment] 2023-11-30 08:34
That's true -- `#[googletest::test]` modifies the test function to return a `Result` indicating whether the test passed or failed. This facilitates test failures which don't panic, since panicking is too expensive in the context where GoogleTest will be used.

It should be possible to modify the `#[googletest::test]` macro to detect `#[should_panic]` and treat that as a special case, but before we try that, I'd like to clarify what you are trying to do with this. Namely, how should `expect_that!` failures be handled in that setup? Should they also trigger a panic (which would invert the meaning of the test)?

**Comment by hovinen** [comment] 2023-11-30 20:58
All right. Are you looking for a way to take a full-blown test and say, "this is expected to fail", in the sense that the test function should remain untouched?

Or are you looking just for a way to invoke a function which contains `expect_that!` assertions which are expected to fail and to see that failure?

The former might be possible by creating an integration test which disables the default Rust test harness but keeps the test annotations. Then you should be able to invoke the function and assert on its output `Result`. If that doesn't work, then we may need to special-case `#[should_panic]`.

The latter is doable by digging into the same APIs which `#[googletest::test]` itself uses. One can register a test context, invoke the method, and then check whether it failed or not. In fact, there's even a public API for checking whether a failure has been registered: https://docs.rs/googletest/latest/googletest/fn.verify_current_test_outcome.html.

**Comment by LukeMathWalker** [comment] 2024-01-05 13:14
> It's not pressing, but I think it'll come up again as people use the library more.

I second that!
I'm updating [Mainmatter's advanced testing workshop](https://mainmatter.com/services/workshops/advanced-testing-in-rust/) and we're going to be teaching `googletest` as the recommended library for advanced assertions.  
The only part where I find myself falling back to `#[test]` are test cases where I need to use `#[should_panic]`.

**Comment by bjacotg** [comment] 2024-01-07 16:25
I find the behavior in #345 a little surprising. I would prefer a statement level panic expectation similar to `EXPECT_DEATH`. Consider the following test:

```
#[google_test::test]
#[should_panic]
fn panicky_subject() -> Result<()> {
  // Arrange
  let subject = build_subject();
  verify_that!(setup_subject(&subject), ok(anything()))?; // or just setup_subject(&subject)?;
  // Act
  subject.call_panic();
  // "Assert"
  Ok(())
}
```

If the Arrange `verify_that!` fails, then the test would still pass. This can be fixed with an `expected` argument on  `should_panic` or `if let Err(_)  = setup_subject(&subject) { return Ok(());}`.

But an `EXPECT_DEATH`-like solution would be much more complicated and, as @hovinen mentioned, gtest was designed for an environment with few panics. So I will merge #345 for now and file a feature request for an `EXPECT_DEATH` macro.

**Closed** 2024-01-11 17:24 UTC
